name: flask_func_struct_sijax_toc
on:
  push:
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: flask_func_struct_sijax_toc
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
