name: flask_func_struct_sijax_triage_label
on:
  issues:
    types: [opened]
jobs:
  applyTriageLabel:
    name: flask_func_struct_sijax_triage_label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flask_func_struct_sijax_triage_label
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: label triage
